version: "3.9"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - account-service
      - status-service
      - story-service
  db-account:
    image: mongo:4.0-xenial
    ports:
      - 27014:27017
    volumes:
      - account:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_INITDB_ROOT_DATABASE: root-db
  db-status:
    image: mongo:4.0-xenial
    ports:
      - 27015:27017
    volumes:
      - status:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_INITDB_ROOT_DATABASE: root-db
  db-story:
    image: mongo:4.0-xenial
    ports:
     - 27016:27017
    volumes:
      - storynew:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_INITDB_ROOT_DATABASE: root-db

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - object:/data

  account-service:
    build: ./userService
    restart: unless-stopped
    depends_on:
      - db-account
    environment:
      DB_URL: mongodb://db-account:27017/AccountDatabase

  status-service:
    build: ./statusService
    restart: unless-stopped
    depends_on:
      - account-service
      - db-status
    environment:
      DB_URL: mongodb://db-status:27017/StatusDatabase
  story-service:
    build: ./storyService
    restart: unless-stopped
    depends_on:
      - db-story
      - account-service
      - storyobjectdb
    environment:
      DB_URL: mongodb://db-story:27017/StoryDatabases
  
  
volumes:
  status:
  account:
  object:
  storynew: